services:
  - type: web
    name: farunqingmiao
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run server:build
    startCommand: npm run server:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: ./data
      sizeGB: 1